CONFIG = {
    "largura": 1920,
    "altura": 1080,
    "fps": 24,
    "cor_fundo": (255, 183, 77),
    "cor_texto": (255, 255, 255),
    "cor_contorno": (0, 0, 0),
    "espessura_contorno": 2,
    "caminho_fonte": "C:\\Windows\\Fonts\\arialbd.ttf",
    "tamanho_fonte": 200,
    "tempo_animacao": 3.0,
    "tempo_pausa": 1.5,
    "tempo_final_extra": 5,
    "valores_marcos": [1, 5, 10],
    "efeito_piscar_final": True,
    "cores_piscar": [(255, 255, 255), (255, 215, 0)],
    "piscar_por_segundo": 6,
    "arquivo_saida": "video_contador_configuravel.mp4",
    "texto_unidade_monetaria": "R$",
    "tempo_animacao_aleatorio": False,
    "intervalo_tempo_animacao": [2.0, 4.0],
    "fator_inicio_suave": 1.0,
    "fator_fim_suave": 1.0,
}
